config/routes.rb
Rails.application.routes.draw do
  mount Split::Dashboard, at: 'split'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    collection do
      get :autocomplete
      get :me
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords',
    registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  
  get 'welcome' => 'welcome#index'
  root 'welcome#index'
end

app/models/question.rb
# Questions - ask whatever you like
class Question < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :answers, dependent: :destroy

  scope :latest, -> { order(:created_at).take(10) }

  validates :title, presence: true
  validates :content, presence: true

  searchkick word_start: [:title, :content], suggest: [:title], highlight: [:title]

  def search_data
    {
      title: title,
      content: content
    }
  end

  def owner?(current_user)
    current_user == self.user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :me]
  before_action :owns_question, only: [:edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    query = params[:q].presence || "*"
    @questions = Question.search(query, suggest: true)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answers = @question.answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /questions/autocomplete
  def autocomplete
    render json: Question.search(params[:term], fields: [{ title: :text_start }],
      limit: 10).map(&:title)
  end

  # GET /questions/autocomplete
  def me
    @questions = current_user.questions
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :content)
    end

    def owns_question
      raise 'must be owner' unless user_signed_in? && @question.owner?(current_user)
    end
end

app/views/questions/_answer.html.erb
<li class="media mb-2" data-id="<%= answer.id %>">
  <%= user_avatar(current_user, klass: 'mr-3')%>
  <div class="media-body">
    <div class="mb-1"><%= answer.content %></div>
    <p class="mt-0 mb-1 small"><%= answer.user.name %> answered <%= local_time_ago(answer.created_at) %></p>
  </div>
</li>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div class="alert alert-warning" id="error_explanation">
      <h6 class="">
        <%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:
      </h6>
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :question_title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :question_content, class: 'form-control' %>
  </div>
  <% if user_signed_in? %>
    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-outline-success' %>
    </div>
  <% else %>
    <div class="actions">
      <button class="btn btn-outline-secondary disabled">Submit</button>
    </div>
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<h2 class="text-center">
  Edit question
</h2>
<p class="text-center"><%= link_to 'cancel changes', @question, class: 'small' %></p>
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<h2 class="text-center">Questions</h2>
<% if @questions.suggestions.any? %>
  <p>Did you mean: <strong><%= @questions.suggestions.first %></strong></p>
<% end %>
<%= @questions.response %>
<div class="list-group">
<% @questions.with_highlights.each do |_, highlights| %>
  <%= highlights[:title] %>
<% end %>
  <% @questions.each do |question| %>
    <a href="<%= question_path(question) %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= question.title%></h5>
        <small><%= local_time_ago(question.created_at) %></small>
      </div>
      <div class="mb-1"><%= question.content %></div>
    </a>
  <% end %>
</div>

app/views/questions/me.html.erb
<h2 class="text-center">My Questions</h2>
<div class="list-group">
  <% @questions.each do |question| %>
    <a href="<%= question_path(question) %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= question.title %></h5>
        <small><%= local_time_ago(question.created_at) %></small>
      </div>
      <div class="mb-1"><%= question.content %></div>
    </a>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="">
  <h5>Ask the community for advice, recommendations, best food...</h5>
  <%= render 'form', question: @question %>
  <% unless user_signed_in? %>
    <div class="alert alert-warning my-3 text-center">
      Sign up to ask the community a question
      <%= Emoji.find_by_alias("thinking").raw %>
    </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<div class="d-flex justify-content-start mb-3">
  <span class="mr-auto text-muted">
    <span class="text-dark"><%= @question.user.name %></span> asked on
    <span class="text-dark"><%= local_time(@question.created_at) %></span>
  </span>
  <%= link_to 'Edit', edit_question_path(@question), class: '' if user_signed_in? && @question.owner?(current_user) %>
</div>
<div class="">
  <%= @question.content %>
</div>
<hr />
<ul class="list-unstyled mb-4" id="answers">
  <% @answers.each do |answer| %>
    <%= render 'answer', answer: answer %>
  <% end %>
</ul>
<%= form_with(model: @answer, url: question_answers_path(question_id: @question.id)) do |form| %>
  <% if @answer.errors.any? %>
    <div class="alert alert-warning" id="error_explanation">
      <h6 class="">
        <%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:
      </h6>
      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :content, 'Your answer' %>
    <%= form.text_field :content, id: :answer_content, class: 'form-control' %>
  </div>
  <% if user_signed_in? && !@question.owner?(current_user) %>
    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-outline-success' %>
    </div>
  <% elsif @question.owner?(current_user) %>
    <div class="actions">
      <button class="btn btn-outline-secondary disabled" type="button">Submit</button>
    </div>
    <div class="alert alert-warning my-3 text-center">
      You are awesome, but you can't answer you own question
      <%= Emoji.find_by_alias("raised_hands").raw %>
    </div>
  <% else %>
    <div class="actions">
      <button class="btn btn-outline-secondary disabled" type="button">Submit</button>
    </div>
    <div class="alert alert-warning my-3 text-center">
      Sign up to answer questions, and be awesome!
      <%= Emoji.find_by_alias("raised_hands").raw %>
    </div>
  <% end %>
<% end %>