config/routes.rb
Rails.application.routes.draw do
  mount Split::Dashboard, at: 'split'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    collection do
      get :autocomplete
      get :me
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords',
    registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  
  get 'welcome' => 'welcome#index'
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @questions = Question.latest
  end
end

app/views/welcome/index.html.erb
<h1 class="text-center mb-5">Ask away. Anything you like!</h1>
<%= form_tag(questions_url, method: "get") do %>
  <%= text_field_tag(:q, nil, id: 'question-time', class: 'form-control form-control-lg', placeholder: 'Search for...' ) %>
<% end %>
<div class="mt-5">
  <p class="text-center">
    <% ab_test(:new_question_link_class, "btn-primary", "btn-outline-primary") do |alternative| %>
      <%= link_to 'New Question', new_question_path, class: "btn #{alternative}" %>
    <% end %>
  </p>
  <% unless @questions.any? %>
    <p class="text-center display-1">🤷</p>
    <p class="text-center">No questions submitted.</p>
  <% else %>
    <h6 class="text-center">Latest questions <%= Emoji.find_by_alias("cat").raw %></h6>
    <div class="list-group">
      <% @questions.each do |question| %>
        <a href="<%= question_path(question) %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= question.title %></h5>
            <small><%= local_time_ago(question.created_at) %></small>
          </div>
          <div class="mb-1"><%= question.content %></div>
        </a>
      <% end %>
    </div>
  <% end %>
</div>