config/routes.rb
Rails.application.routes.draw do
  mount Split::Dashboard, at: 'split'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    collection do
      get :autocomplete
      get :me
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords',
    registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  
  get 'welcome' => 'welcome#index'
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>askaway</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">askaway</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-success font-weight-bold" href="<%= new_question_path %>">New question</a>
          </li>
        </ul>
        <% unless current_page?(root_url) %>
          <%= form_tag(questions_url, method: "get", class: 'form-inline my-2 my-lg-0') do %>
            <%= text_field_tag(:q, nil, class: 'form-control', placeholder: 'Search for...' ) %>
          <% end %>
        <% end %>
        <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <%= user_avatar(current_user)%>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <h6 class="dropdown-header">Hi, <%= current_user.name %></h6>
              <a class="dropdown-item" href="<%= edit_user_registration_url %>">Edit profile</a>
              <%= link_to('My questions', me_questions_url, class: 'dropdown-item') %>
              <a class="dropdown-item" href="#">My claps</a>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete,
                class: 'dropdown-item'  %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path,
              class: 'nav-link font-weight-bold text-primary'  %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <div role="alert"
        class="alert text-center <%= name == 'alert' ? 'alert-warning': 'alert-success'%> alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= msg %>
      </div>
    <% end %>
    <div class="col-md-8 col-lg-6 mx-auto py-5"><%= yield %></div>
  </body>
</html>